name: Monitor Rhys Williams Posts

on:
  schedule:
    # Run every 15 minutes between 10:00 and 14:00 UTC (adjust timezone as needed)
    - cron: "0,15,30,45 10-13 * * *" # Every 15 mins from 10:00-13:45 UTC
    - cron: "0 14 * * *" # Final check at 14:00 UTC
  workflow_dispatch: # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check Rhys Williams Posts
        run: |
          echo "🔍 Checking for new Rhys Williams posts..."

          response=$(curl -s "${{ secrets.VERCEL_URL }}/api/check-rhys")
          echo "Response: $response"

          # Check if the response contains success: true
          if echo "$response" | grep -q '"success":true'; then
            echo "✅ Monitor check completed successfully"
            
            # Check for new posts
            if echo "$response" | grep -q '"newPosts":[1-9]'; then
              echo "🎉 New Rhys Williams posts found!"
            else
              echo "📭 No new posts found"
            fi
          else
            echo "❌ Monitor check failed"
            echo "$response"
            exit 1
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Monitor check failed!"
