name: Rhys Williams Monitor

on:
  schedule:
    # Run every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [main]
    paths: [".github/workflows/rhys-monitor.yml"] # Only run on workflow changes

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check Rhys Williams Posts
        run: |
          echo "🔍 Checking for new Rhys Williams posts..."

          response=$(curl -s -w "\n%{http_code}" "${{ secrets.VERCEL_API_URL }}/api/check-rhys")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)

          echo "HTTP Status: $http_code"
          echo "Response: $body"

          if [ "$http_code" -eq 200 ]; then
            echo "✅ Successfully checked for posts"
            
            # Parse response to check if new posts were found
            new_posts=$(echo "$body" | jq -r '.newPosts // 0')
            message=$(echo "$body" | jq -r '.message // "No message"')
            
            echo "New posts found: $new_posts"
            echo "Message: $message"
            
            if [ "$new_posts" -gt 0 ]; then
              echo "🎉 $new_posts new posts found and alerts sent!"
            else
              echo "📭 No new posts found"
            fi
          else
            echo "❌ Error: HTTP $http_code"
            echo "$body"
            exit 1
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Monitor check failed!"
          # You could add additional failure notifications here
