name: Monitor Rhys Williams Posts

on:
  schedule:
    # Run every 5 minutes between 9:30 and 12:30 UTC
    - cron: "30,35,40,45,50,55 9 * * *" # 9:30-9:55 (6 runs)
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 10-11 * * *" # 10:00-11:55 (24 runs)
    - cron: "0,5,10,15,20,25,30 12 * * *" # 12:00-12:30 (7 runs)
  workflow_dispatch: # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check Rhys Williams Posts
        run: |
          echo "🔍 Checking for new Rhys Williams posts..."

          response=$(curl -s "${{ secrets.VERCEL_URL }}/api/check-rhys")
          echo "Response: $response"

          if echo "$response" | grep -q '"success":true'; then
            echo "✅ Monitor check completed successfully"
            
            if echo "$response" | grep -q '"newPosts":[1-9]'; then
              echo "🎉 New Rhys Williams posts found!"
              
              # Extract email status
              if echo "$response" | grep -q '"emailSent":true'; then
                echo "📧 Email notification sent!"
              fi
            else
              echo "📭 No new posts found"
            fi
          else
            echo "❌ Monitor check failed"
            echo "$response"
            exit 1
          fi

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Monitor check failed!"
