name: Monitor Rhys Williams Posts

on:
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch: # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check Rhys Williams Posts
        run: |
          echo "🔍 Checking for new Rhys Williams posts..."
          curl -f "${{ secrets.VERCEL_URL }}/api/check-rhys"
          echo "✅ Monitor check completed"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Monitor check failed!"
